{% set name = "argparse-dataclass" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/argparse_dataclass-{{ version }}.tar.gz
  sha256: 09ab641c914a2f12882337b9c3e5086196dbf2ee6bf0ef67895c74002cc9297f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - argparse_dataclass
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mivade/argparse_dataclass
  summary: Declarative CLIs with argparse and dataclasses
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johanneskoester
